server:
  port: 8888
#  servlet:
#    context-path: /user

spring:
  application:
    name: db_connect_user_crud

  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: 123123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true