server:
  port: 8080
  servlet:
    context-path: /users

spring:
  application:
    name: db_connect_user_crud

  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: 123123123